[package]
name = "melba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = "0.7.10"
tokio = {version = "1.37.0", features = ["full"]}
sqlx = {version = "0.7.4", features = ["runtime-async-std-native-tls","postgres", "migrate", "chrono"]}
reqwest = { version = "0.12.5", features = ["json"] }
serde_json = "1.0.116"
linkify = "0.10.0"
serde = { version = "1.0.198", features = ["derive"] }
chrono = { version = "0.4.38", features = ["serde"] }
dotenv = "0.15.0"
clap = {version = "4.5.7", features = ["color", "derive"]}
colorize = "0.1.0"
thiserror = "1.0.61"
config = "0.14.0"
once_cell = "1.19.0"
sentry = "0.34.0"
prometheus = {version = "0.13.4", features = ["push"]}
log = "0.4.14"
env_logger = "0.11.5"

[lib]
path = "src/lib.rs"

[[bin]]
name = "melba"
path = "src/main.rs"

[dev-dependencies]
mockito = "1.4.0"
