debug = true

[wayback_machine_api]
myaccesskey = "OqvSkX8Sv5hblwrv"
mysecret =  "tjow7aOFJAWokDsX"

[retry_task]
retry_interval = 120 # 2 min
allow_remove_row_after = 600 # 10 min

[sentry]
url = "your sentry DSN here"

[database]
pg_host = "localhost" # If running as a docker container, change this to musicbrainz-docker-db-1
pg_port = 5432
pg_user =  "musicbrainz"
pg_password = "musicbrainz"
pg_database =  "musicbrainz_db"
database_url = "postgres://musicbrainz:musicbrainz@localhost:5432/musicbrainz_db"